### ISSUE TITLE
upload组件支持单独获取后台返回的某个数据

### ISSUE THREAD

**Issue by BingBlog** [JSON-Drived-Configurable-Platform/cp#42]

**Comment by BingBlog** [comment]
https://github.com/JSON-Drived-Configurable-Platform/form-generator-iview/pull/41

**Comment by BingBlog** [comment]
I think this is a great idea for all the components that receive data from remote;
Can we just make it a common config for all the components?

**Comment by xiaomiCat** [comment]
closed #42 This problem has been solved！
